// @/lib/grok.ts

export async function generateMultiAngleConcept(seedIdea: string, category: string) {
  const apiKey = process.env.GROK_API_KEY;

  if (!apiKey) throw new Error("API Key hilang! Cek Environment Variables di Vercel.");

  try {
    const response = await fetch('https://api.x.ai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: "grok-beta",
        messages: [
          {
            role: "system",
            content: `You are an expert ${category} creator. 
            Analyze the user's idea and expand it into a high-potential project.
            
            STRICT RULES:
            1. Return ONLY a JSON object.
            2. Language: Match the user's language (Indonesian/English).
            3. NoveltyScore must be an integer between 1-100.`
          },
          {
            role: "user",
            content: `Create a concept from this idea: "${seedIdea}"`
          }
        ],
        temperature: 0.8,
        response_format: { type: "json_object" }
      }),
    });

    if (!response.ok) {
      const errorMsg = await response.text();
      throw new Error(`Grok Error: ${response.status} - ${errorMsg}`);
    }

    const data = await response.json();
    const rawContent = data.choices[0].message.content;

    // Kadang AI ngasih markdown ```json ... ```, kita bersihin biar gak error pas parse
    const cleanJson = rawContent.replace(/```json|```/g, "").trim();
    const result = JSON.parse(cleanJson);

    return {
      title: result.title || "Untitled Masterpiece",
      description: result.description || "Freshly generated by Originix AI.",
      fullConcept: result.fullConcept || "Detailed concept coming soon.",
      noveltyScore: Number(result.noveltyScore) || 85
    };

  } catch (error: any) {
    console.error("Critical Failure in Grok Lib:", error.message);
    // Fallback data biar user gak dapet layar putih
    return {
      title: "Idea: " + seedIdea.slice(0, 30),
      description: "AI sedang sibuk, tapi ide lu keren banget!",
      fullConcept: "Gagal generate detail karena masalah teknis: " + error.message,
      noveltyScore: 50
    };
  }
}
